[mypy]
follow_imports = silent
ignore_missing_imports = True

;check_untyped_defs = True
;disallow_incomplete_defs = True
;disallow_subclassing_any = True
;disallow_untyped_calls = True
;disallow_untyped_decorators = True
;disallow_untyped_defs = True
;no_implicit_optional = True
;warn_redundant_casts = True
;warn_return_any = True
;warn_unused_configs = True
;warn_unused_ignores = True
;
;[mypy-quml.clients.pylabclient,quml.servers.pylabinterface,quml.zmq_interface.*]
;check_untyped_defs = False
;disallow_incomplete_defs = False
;disallow_subclassing_any = False
;disallow_untyped_calls = False
;disallow_untyped_decorators = False
;disallow_untyped_defs = False
;no_implicit_optional = False
;warn_redundant_casts = False
;warn_return_any = False
;warn_unused_configs = False
;warn_unused_ignores = False
